spring:
  cloud:
    stream:
      bindings:
        output:
          destination: test
          binder: kafka
        processMeta:
          destination: test
          binder: kafka
        datasetMeta:
          destination: test
          binder: kafka
      kafka:
        binder:
          brokers: 10.10.70.179:9092
          zkNodes: 10.10.70.180:5181
          configuration.streams.consumer.default.stream: /tmp/kafka
          configuration.streams.producer.default.stream: /tmp/kafka
          
